### ISSUE TITLE
Before-the-fact data quality (Prevent mistakes before they happen) (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#10272]
### Data destroying issues in production right now
[List of data destroying issues in production right now](https://github.com/openfoodfacts/openfoodfacts-server/labels/data%20destroying%20issue)

```[tasklist]
### Product addition
- [ ] #170
```

```[tasklist]
### Spellcheck
  - [ ] #937
```

```[tasklist]
### On-the-fly checks
- [ ] #1905
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/6539
- [ ] #9710
```

```[tasklist]
### Edit rules
- [ ] #798
- [ ] #2909
- [ ] #4362
- [ ] #904
```
```[tasklist]
#### Edit rules - Nutrition
- [ ] #1564
- [ ] #1759
```
```[tasklist]
#### Ingredient list blocklist
- [ ] #796
```
```[tasklist]
### Taxonomy special characters
- [ ] #458
```
```[tasklist]
### Ingredients consistency (languages)
- [ ] #422
```
```[tasklist]
### Old data
- [ ] #58
```
```[tasklist]
### Verification
- [ ] #1438
```
```[tasklist]
### Making quality more visible
- [ ] #1407
```
```[tasklist]
## Remediation
```
```[tasklist]
### Quality facets 
- [ ] #1119
```
```[tasklist]
### Images
- [ ] #1092
```
```[tasklist]
### Anonymous edits & UUIDs
- [ ] #1091
- [ ] #3431
- [x] #3849
- [ ] #1019
```
### In place edit
```[tasklist]
#### image rotation
- [ ] #998
```
```[tasklist]
### Tackle variable barcodes
- [ ] #975
```
```[tasklist]
### Ingredient analysis (false positives)
- [ ] #944
```
```[tasklist]
### Ingredients/Label coherence
- [ ] #913
- [ ] NutriScore label coherence
- [ ] [Robotoff - Make the Nutri-Score prediction notifications actionable](https://github.com/openfoodfacts/robotoff/issues/317)
```
```[tasklist]
### Ingredients
- [ ] #910
- [ ] #907
```
