### ISSUE TITLE
(RfC) Allow the product page to display external Knowledge-panel spec compliant data

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#10297]
### Why
- We have more and more external backends providing information that belongs on the product page (Nutri-Patrol, Open Prices, Folksonomy Engine)
- We have somewhat integrated Folksonomy Engine, but the integration leaves to be desired
- We have yet to integrate Nutri-Patrol and Open Prices
### What
- Make Nutri-Patrol, Open Prices, Folksonomy Engine Knowledge-panel spec compliant
- Allow the product page to display external Knowledge-panel spec compliant data
- Display those external backends within the product page using JS

### Beyond
- We could consider making Robotoff and Hunger Games compliant as well, as well as any new project we start
- The new use cases would provide a stronger incentive to evolve and complete the KP syntax, for the benefit of the web and the mobile app

cc @stephanegigandet @alexgarel @hangy @john-gom @Valimp @4nt0ineB @raphael0202 for comments
### Related issues

- [ ] [Create a Knowledge Panel route for each product, so that we can integrate it in the ProductOpener Product Page openfoodfacts/open-prices#316](https://github.com/openfoodfacts/open-prices/issues/316)
- [ ] [Integrate Nutri-Patrol in The Open Food Facts website openfoodfacts/nutripatrol#56](https://github.com/openfoodfacts/nutripatrol/issues/56)
- [ ] [Create a Knowledge Panel compliant route for the Folksonomy Engine list of properties for a given barcode openfoodfacts/folksonomy_api#185](https://github.com/openfoodfacts/folksonomy_api/issues/185)

### Part of
- #5493

**Comment by teolemon** [comment]
Additional benefit, this could be the ground for making Knowledge Panel rendering a separate backend in Python
