### ISSUE TITLE
Categorisation quality

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#10841]
### Description
At the moment there are very few checks  on the categorisation quality. A user can do what he likes and sees fit. And OFF has no ways of checking this. There are small steps made towards monitoring the categorisation (thinking of olive oils). Likely more can be done, which we can define here.

### Acceptance criteria
The end-situation should be that every category has its monitoring parameters. It would be great that the monitoring happens live, so that a users sees it immediately when she/he inputs the wrong category.

### What would a demo look like
Error messages such are used now for nutritional quality checks and similar to single ingredient checks.

### Notes
The parameters for these checks can be either encoded in the taxonomy or calculated;

### Tasks
- [X ] Single ingredient checks - for categories that can only have ONE ingredient
- [ ] Multiple ingredient checks - for products that contain multiple ingredients (2 or more) and exactly those ingredients.
- [ ] Minimally required ingredients - for products that should have at least these (1 or more) ingredients. For instance Asparagus soups should at least contain the ingredient asparagus. And canned asparagus should contain the ingredient asparagus AND water;
- [ ] Nutritional envelopes - for each category an envelope for acceptable values can be defined. If a product is entered outside this envelope a warning should be triggered;
