### ISSUE TITLE
Graphics improvement

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#10856]
### Description
The OFF graphics module is already powerful, but can be extended with other graphing options. This would allow even better analysis of the data. This is also useful to visually detect problematic products.

### What would a demo look like
Show me the graph.

### Notes
* There are many possibilities, which easily can complicate things, so this should be done step by step. And only when the usefulness is demonstrated.
* See also [Visualisation](https://wiki.openfoodfacts.org/Visualisation)

### Tasks
- [ ] [Box plots](https://en.wikipedia.org/wiki/Box_plot)
- [ ] [Violin plots](https://en.wikipedia.org/wiki/Violin_plot)
- [ ] Combined box/violin plots
- [ ] Simple fits
- [ ] CSV export supported for graph data, so that one continue an analysis in more dedicated tools

**Comment by alexgarel** [comment]
@aleene search-a-licious is using Vega to make plot. 

We have to support more plot type there.

The widget to create plot is not yet develop, but it should not be too hard.

**Comment by aleene** [comment]
Can I play with that?
