### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#10855]
### Description
The statistics module now presents some standard information (mean, deviation, min, max, 10%, median). This could be extended to include parameters to detect/identify outliers. This can be used to identify products in the distribution with strange values.
Estimates for a [beta distribution](https://en.wikipedia.org/wiki/Beta_distribution), which will provide better means and deviations as well for the nutrients. Nutrients lie on a bounded interval, which means that a normal distribution is not applicable.
It should be possible to retrieve the statistics data through an API.

### Acceptance criteria
For a demo category we could define the acceptable values that can be checked;

### What would a demo look like
The statistics information on a facet page could include the new information;

### Notes
* Do not use upper limits in the statistics calculation;
* Suppress the 10% quantiles and replace them with 25% quartiles;

### Tasks
- [ ] Define calculations for the required statistics
- [ ] Setup the calculations
- [ ] Expose the values on web
- [ ] Expose the values on API
- [ ] Use boundaries to raise product flags
- [ ] Add flags to data quality monitoring
