### ISSUE TITLE
Extend language support stopgap

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#10854]
### Description
The goal is to support some language (variants) that are in high demand and can not be supported today. These languages probably will not be supported in the near future. This should apply only to languages with many potential users and that are sufficiently different (in some cases)

### Acceptance criteria
The solution should fit within the current approach to languages, i.e. 2 letter ISO-codes. In this standard the range xa-xz is reserved for end-users. We could assign some of these to specific languages.

### What would a demo look like
We could set up some demo products that will be correctly parsed.

### Notes
This might be needed for the following languages
* traditional Chinese (XT) - the default is simplified Chinese (ZH);
* Brasilian Portuguese (XB) - the default is Portugal Portuguese (PT);
* Quebecois (XQ) - the default is France French (FR)
* American English (XA) - the default is British English (EN)

### Tasks
- [ ] Add the languages to the languages taxonomy;
- [ ] Adapt the country languages as needed;
- [ ] Support a language trickle down (if a translation does not exist, user another language, if that does not exist use another, etc. This might be needed for correct parsing as well.
- [ ] Start adding the correct translations to the other taxonomies;

**Comment by alexgarel** [comment]
@aleene in the medium run, it would be better to support two letters languages codes.

**Comment by aleene** [comment]
That is what I suggest, no?

**Comment by teolemon** [comment]
### Related to
- https://github.com/openfoodfacts/openfoodfacts-server/issues/6688 (which is a P1)
