### ISSUE TITLE
Add Expected energy as nutrient

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-server#10862]
### Description
The expected energy is the energy expected based on the values for the nutrients and a standard formula. This expected energy should be the same as the published energy. Any large deviations indicate a problematic product. In a scatter plot these are easily seen and can be inspected and corrected.
Large deviations in the energy difference (publish energy minus expected energy) can be used as a flag for data quality.

### Acceptance criteria
Some test to check the correctness of the formula based on a specific complex product.

### What would a demo look like
A scatter plot with published energy versus expected energy for a category.

### Notes
* See the [wiki](https://wiki.openfoodfacts.org/Nutrients/Energy_(expected-ico));
* Exclude upper values from calculations;

### Tasks
- [ ] Add the expected nutrient to nutrients taxonomy;
- [ ] Implement the formula and calculations for each product;
- [ ] Add the expected energy to the statistics and graph module;

**Comment by aleene** [comment]
This is availabe through the Power user script, which is enough for the moment.
