### ISSUE TITLE
Ingredients knowledge panel (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#10906]
### What
- [ ]  #9944 
- [ ] #8583 
- [ ] #7041 
- [ ] #6499 
- [ ] #5632 
- [ ] #832 
- [ ] Refactor the NOVA kp to use the new ingredients kp
- [ ] Refactor the ingredient analysis panel to merge it in the ingredients kp (possibly with an advanced mode)
- [ ] Refactor the ingredient detection panel (vegan, palm oil, etc…) to use the new ingredients kp 
- [ ] Add linked ingredients KP (or something else) to the attributes (especially allergens)
- [ ] Add special support for ingredients that are allergens
- [ ] Add special support for ingredients that are additives (link to the additives KP)
- [ ] Add a deeplink to the taxo editor on individual unrecognized ingredients

### Part of
- #5493
