### ISSUE TITLE
Improve the "Recent Changes" screen

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#10948]
### What
- [ ] [Make detected quality issues visible to moderators in "Recent changes" | openfoodfacts-server#2952](https://github.com/openfoodfacts/openfoodfacts-server/issues/2952)
- [ ] [Filter Recent Changes by user group (app, bots…) | openfoodfacts-server#2125](https://github.com/openfoodfacts/openfoodfacts-server/issues/2125)
- [ ] [Create warning for "Not indicated" values | openfoodfacts-server#2782](https://github.com/openfoodfacts/openfoodfacts-server/issues/2782)

### Part of
- #5538
