### ISSUE TITLE
🤳🥫 https://scan.party (Tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1188]
### What
- [ ] http://scan.party/

### Tasks
- [ ] Commit scan.party code in GitHub
- [ ] Check with @stephanegigandet where this code lives (main server, something else)
- [ ] Check with @alexgarel whether he found related files during the migration
- [ ] Fix the SSL issue on http://scan.party/

### Part of
- #5529
