### ISSUE TITLE
Split JavaScript and HTML

### ISSUE THREAD

**Issue by NerOcrO** [openfoodfacts/openfoodfacts-server#1533]
## Why

- more efficiant
- more readable
- less difficult merges
- good practice

## TODO

- [x] remove some useless JavaScript in html/js
- [ ] remove html/bower_components
- [ ] remove gulp and change it with webpack
- [ ] clean package.json
- [ ] make just 1 JavaScript file

**Comment by hangy** [comment]
Related #1182. Unfortunately, there is some challenge in balancing webpack and the dynamically created JavaScript (especially global variables).

**Comment by NerOcrO** [comment]
Thanks for related topic.
