### ISSUE TITLE
Meta bug for Portuguese translation issues

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1730]
- [ ] https://pt.openfoodfacts.org/parceiros
- [x] https://pt.openfoodfacts.org/codigo-de-conduta / https://pt.openfoodfacts.org/quem-somos / https://pt.openfoodfacts.org/perguntas-frequentes / https://pt.openfoodfacts.org/imprensa
- [x] descobrir and contribuir

- [ ] Weird translation in advanced search
![image](https://user-images.githubusercontent.com/1689815/55228953-de60ef00-521b-11e9-95e7-1bc587efff8f.png)

**Comment by teolemon** [comment]
Ok, mostly fixed.
2 points still here
