### ISSUE TITLE
Automate emails sent to producers on various lifecycle events for an org

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5012]
### What

```[tasklist]
### Tasks
- [ ] Email admins on various lifecycle events for an org
- [ ] Email admins on initial file upload for an org (with a link to the file potentially + email)
- [ ] Email admins on initial product creation from XLS file (with a link to the org + email)
- [ ] Email admins on first manual product creation (with a link to the org + email)
```

### Part of
- #5730
- #5521

**Comment by manon-corneille** [comment]
Some email ideas we could sent automatically: https://docs.google.com/spreadsheets/d/13BKG27wIXu1A8N7a-jBSe3NVqfKEarn3c4mt4NzRhgc/edit#gid=0

**Comment by alexgarel** [comment]
see https://github.com/openfoodfacts/openfoodfacts-server/issues/7296 for this should be done on CRM side.

**Comment by manon-corneille** [comment]
I close because this is going to be done via Odoo
