### ISSUE TITLE
🔎 Search (epic)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5492]
### Who for

- As a user, I want to find a specific product quickly (eg first result)
- As a user, I want to find a list of products matching my preferences, with the better fits on top

> [!WARNING]  
> We are starting an ambitious project to extract search from Producer Opener (the server), and overhaul it using Modern Technologies. https://github.com/openfoodfacts/search-a-licious
> We are also reimplementing Search-A-Licious based search on the future frontend of Open Food Facts https://github.com/openfoodfacts/openfoodfacts-explorer
> All efforts should be channeled in that project

### LEGACY CURRENT SEARCH - USEFUL FOR REFERENCE
- [Old Design doc](https://docs.google.com/document/d/1_czdNCSg53rcaFP9t_bmVSAFDgR120ZW9C1mOV4aWec/edit)
### Change the search backend to allow for more powerful, more scalable, faster search
- [ ] #1510 (probably not powerful enough)
#### Make more fields and things searchable
- [ ] #155
- [ ] #18
- [ ] #3333
- [ ] #915
- [ ] #516
- [ ] #2762
- [ ] #169 (bug)
- [ ] #191

#### Limit search to specific fields
- [ ] #903
- [x] #485

#### Use consistent wording with the product page
- [ ] #17

#### Improve search performance
- [ ] #425 (people add “nutrition” which yields 0 results)

#### Add more results visualisation options
- [ ] #2916

#### Better 0 result experience
- [ ] #3362

#### Multilingual search
- [ ] #1918

#### Rank and sort search results better
- [ ] #2172
- [ ] #158

### Mobile Search
Please see the cross-platform [mobile search tracker](https://github.com/openfoodfacts/smooth-app/issues/991)

#### Add search autocomplete
- [ ] #1120
  - [ ] #343
- [ ] #389
- [ ] #5006

#### (Mobile/Web) Add search knowledge cards
- #168

### Allow natural language search queries 
- [ ] “Show me ready made meals that are NutriScore A sold at Aldi”
- [ ] “Show me the repartition of NutriScore for Nestlé in Europe”
- [ ] “Make me a graph of all breakfast cereals with NOVA groups, nutrition value and Nutri-Score”

#### Improving the country of sale field
- [ ] #5514 

### Why
- Regular users rely on Open Food Facts to find the best products for them
- Producers rely on Open Food Facts to benchmark their products
### Part of
- #5529

**Comment by Infinimus01** [comment]
Hi @teolemon ,I’d love to contribute to the Search-a-licious project.
I’m comfortable with JavaScript and Node.js and would like to start with a small issue related to search or UI.
Could you please recommend a good starting point?

**Comment by teolemon** [comment]
@Infinimus01 the action happens in https://github.com/openfoodfacts/search-a-licious/issues
@alexgarel and @raphael0202 are the key referents. 
Are you on the Open Food Facts Slack yet ? We have a channel for Search-A-Licious.
