### ISSUE TITLE
Knowledge Panel - Deforestation/Forest footprint

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5495]
### Who for
- Developers
### What
- [Design doc](https://docs.google.com/document/d/15a-atqbxVbWeslcqzfO1q3hVs12t7KQPHhFCZ8bWoc8/edit)

### Tasks
- [ ] Show the impact of the product in terms of deforestation
- [ ] Add the link to the Forest footprint methodology in the Forest footprint attribute: https://fr.openfoodfacts.org/empreinte-foret-des-produits-alimentaires
- [ ] Translate the forest footprint in English: https://github.com/openfoodfacts/openfoodfacts-web/pull/419

### Part of 
- #5493

**Comment by stephanegigandet** [comment]
Duplicate of #8588
