### ISSUE TITLE
European extension of the Eco-Score

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5503]
#### Ingredient analysis
- [ ] Internationalize text analysis support for ingredients
- [ ] Internationalize text analysis support for origins within ingredients
- [ ] Internationalize text analysis support for packaging information
- [ ] Internationalize palm oil detection
#### Distances
- [ ] Recompute transportation for all countries in the world
- [ ] Add a system to crowdsource recycling systems across the world
- [ ] Gather open data about recycling systems across the world
- [ ] Encourage semantic standardization about recycling systems across the world
- [ ] Add local equivalents of the Eco-Score labels
#### Categories
  - [ ] Translate category names into more languages
  - [ ] Finish to merge European IGPs
#### Static pages
  - [ ] Automate the deployment of translated static pages
  - [ ] Translate the Eco-Score explanation page
  - [ ] Hide most of the UI when a page is loaded from an OFF app (for Eco-Score explanations)
### Part of
- https://github.com/openfoodfacts/offf/issues/4
