### ISSUE TITLE
Let Product Opener use and cache Wikidata data for entities

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5506]
### Who for
- OFF mobile developers
- Users

### What
- Many taxonomy entries are linked to Wikidata, but we're not using it to the fullest.
- Wikidata is volatile, and entries may change, disappear, or may be vandalized for a period of time
- [ ] Create a Wikidata caching system that fetches data about entities and stores them on the server
- [ ] Expose Wikidata information for consumption within the Knowledge panel API
- [ ] Use the Knowledge panel API to enrich the product page

### Why
- Wikidata provides expanding structured and non-structured info in many languages

**Comment by teolemon** [comment]
Nice tool for Supermarkets: https://nsi.guide/index.html?t=brands&k=shop&v=supermarket&tt=food
