### ISSUE TITLE
Automated deployments

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5511]
#### OFF
- [ ] #5446 
- [ ] #5436

#### Other projects
- [ ] Deploy Open Beauty Facts (prod) automatically
- [ ] Deploy Open Beauty Facts (dev) automatically
- [ ] Deploy Open Pet Food Facts (dev) automatically
- [ ] Deploy Open Pet Food Facts (prod) automatically
- [ ] Deploy Open Products Facts (dev) automatically
- [ ] Deploy Open Products Facts (prod) automatically

### Part of

- [ ] Devops
