### ISSUE TITLE
Gamification (Tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5516]
### Who for
- Contributors
#### Reboot our missions systems
- [ ] #2283
- [ ] #1028
#### Reboot the Teams feature
- [ ] Make it more visible
- [ ] Integrate it in the app
- [ ] Integrate it with missions and food contest
#### Reboot the Food contest feature
- [ ] #156
- [ ] #40
#### Support the mobile apps
- [ ] #898
#### Other
- [ ] #4531
- [ ] #3170
- [ ] #2566
- [ ] #2552
- [ ] #1401
- [ ] #51
- [ ] #49
- [ ] #5
- [ ] #4

### Why
- Make contribution a more playful experience
- Support the gamification of the apps
