### ISSUE TITLE
📸 Open Products Facts (Tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5555]
### What
* https://wiki.openfoodfacts.org/Open_Products_Facts

### Taxonomies
* https://wiki.openfoodfacts.org/Open_Products_Facts_taxonomies

### Add Scores and value-added to Open Products Facts
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/10753
- [ ] #4710
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/10751
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/10752
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/2818
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/1320
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/10756
* https://wiki.openfoodfacts.org/Open_Products_Facts_use_cases
* https://wiki.openfoodfacts.org/Open_Products_Facts_scores

#### Bugs
- [ ] #2664
- [ ] #3942
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/6169
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/2517

##### Editing
- [ ] #2517

#### Bring Additional Fields / Folksonomy to Open Products Facts (to model any product)
- [ ] #1320
- [x] #5556

### Blend Open Food, Products, Beauty and Pet Food Facts together
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/797
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/497

### Mobile app
- https://github.com/openfoodfacts/smooth-app/issues/3923
- https://github.com/openfoodfacts/smooth-app/discussions/1378

### DevOps - Reduce the marginal cost of maintenance of Open Products Facts to 0
- [x] #1536
- [ ] Automate the release of the dev version of Open Products Facts
- [ ] #6408
- [x] Update Open Products Facts to the latest codebase from Open Food Facts
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/8319

### Part of
- #5529
