### ISSUE TITLE
Integrate the Folksonomy Engine directly into Product Opener

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5556]
### What
- We currently test the Folksonomy Engine using a User Script. 
- https://github.com/openfoodfacts/folksonomy_frontend

### Tasks

- [x] Integrate the JavaScript directly in the product page
- [x] Define conditions in which to display it for the beta phase
  - [ ] Always on Open Products Facts when logged in
  - [x] For Power users on Open Food Facts when logged in
- [x] Create the /keys facet for real
- [ ] #6169

### Part of
- #5555
