### ISSUE TITLE
Release the Eco-Score in the United Kingdom

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#5557]
### Who for
- UK users
- UK apps based on Open Food Facts
### What
- [x] Ensure transportation specific to the UK is properly loaded (it is not)
  - https://github.com/openfoodfacts/openfoodfacts-server/blob/main/ecoscore/data/fr_countries.csv
  - #5586 
- [x] Add the United Kingdom to supported countries
- [ ] Ensure we grasp data quick wins
  - [gb-org-05](https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Agb-org-05)
  - [gb-org-02](https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Agb-org-02)
  - [gb-org-04](https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Agb-org-04)
  - [assured-food-standards](https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Aassured-food-standards)
  - [Asda](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=asda)
  - [Lidl](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=lidl)
  - [Aldi](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=aldi)
  - [Morrisons](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=morrisons)
  - [Woolworths](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=woolworths)
  - [Iceland](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=iceland)
  - [Tesco](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=tesco)
  - [Waitrose](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=waitrose)
  - [Sainsbury's](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=sainsburys)
   - [Sainsbury's](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=sainsbury-s)
  - [The-co-operative](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=the-co-operative)
  - [Co-op](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=co-op)
  - [Coop](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=coop)
  - [Marks-and-spencer](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=marks-and-spencer)
  - [John-lewis](https://hunger.openfoodfacts.org/questions?type=brand&value_tag=john-lewis)
- [ ] Write announcements
### Part of
- #5503
