### ISSUE TITLE
When user assign an email to it's profile, it is lower cased

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#5842]
### Description

- On subscription when a user enter an email with upper cases inside, it is automatically registered in lower case format
- On profile, if a user changes hes email for an email with upper cases inside, it is automatically saved in lower case format

### Acceptance criteria

- Old users that have entered an email with upper cases in the past, now have a lowercase email
- if a there is different users for same emails with different cases, the user with upper cases in email is disabled, we only keep the one with the lower cased email
- if a user try a registration with an email with upper case but there is already an existing with same email in lowercase, registrations fails
-  if a user tries to login with an email with upper cases, it is logged in with lower cased email (already implemented in #5812)
-  if a user asks for password reset with an email with upper cases, it is logged in with lower cased email (already implemented in #5812)

### What would a demo look like

* I fill the subscription putting JOhn@example.com as email
* I can login with john@example.com
* if I go in my profile email in john@example.com or JOHN@example.com
* I try to change email in my profile to ALice@example.com
* I confirm the change and logout
* I can login with alice@example.com or ALICE@EXAMPLE.COM
* if I go in my profile the email is lower case.

### Notes
* For old users we need to do a migration script

### Tasks
- [ ] Modify registration to lower case email
- [ ] Modify user profile change to lower case email
- [ ] Make a script to change old users emails that needs to be lowercased

### Part of
- #5809
- #6436
