### ISSUE TITLE
Nginx should display a maintenance page when deployment is in progress

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6111]
- Epic: #

### Description

As a deployment occurs in preprod, nginx should display a maintenance page (ideally with a 503 response code).

### Acceptance criteria

* response is 503 (?)
* a simple page announces that a deployment is in progress (ideally with time when it started)
* alert system should be able not to alert if a deployment is in progress (handle 503 with certain title as ok for a longer time ?)

### What would a demo look like

Make a deployment through replay of last successful deployment.
Got to openfoodfacts.net and see the maintenance page
Verify we are not alerted

### Tasks
- [ ] Make nginx serve maintenance page if it exists (try_file), and return right code
- [ ] Create maintenance.html page, eventually with a start date marker inside
- [ ] Have deploy script mv maintenance.html forth and back, eventually with a sed to set deploy start date 
- [ ] Change alerts to take into account 503 (still they should raise an alert if 503 takes too long)
