### ISSUE TITLE
Create a new group of knowledge panels for producers (not sent by default by the API)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#6326]
### What
- [ ] Create a new group of knowledge panels (not sent by default by the API, but displayed by default on the web for some of them) for producers
- [ ] Candidates
  - [ ] Knowledge panel with a link to the private version of the product on the web version of the producer platform
    - [ ] Would only be displayed for accounts with a producer profile enabled
  - [ ] Platform for Producers promo (sub-Knowledge panel) for everyone ?

### Part of
- #2938 
- #5521

**Comment by manon-corneille** [comment]
To discuss :) I like the knowledge panel idea for producers!
