### ISSUE TITLE
Setup Matomo on our product opener websites

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#6562]
### What
We want to try Matomo on OFF (and equivalent projects) to eventually move away from Google Analytics.

```[tasklist]
### Tasks
- [x] Setup the Matomo script to use it on Open Food Facts
- [ ] Setup the Matomo script to use it on Open Food Facts Producer platform
- [ ] Setup the Matomo script to use it on Open Beauty Facts
- [ ] Setup the Matomo script to use it on Open Pet Food Facts
- [ ] Setup the Matomo script to use it on Open Products Facts
```

### Part of
- https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/108

**Comment by teolemon** [comment]
@alexgarel I reckon this is completely fixed by your ongoing work ?
