### ISSUE TITLE
Data quality: distraction-free editor, focusing on tasks

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-server#7778]
### Description
[Based on aleene wishes]
When Peter wants to fix many products, he would like to focus on some particular tasks:
* fixing ingredients based on photo
* fixing nutrients table based on photo

As a first step, it can be only a distraction-free mode for the current editor.

### Tasks
- [ ] List the different tasks to benefit from distraction-free mode
- [ ] List what to keep and what to hide?
- [ ] Prototype with Power User Script?

**Comment by aleene** [comment]
A page without the need of scrolling would be best.
