### ISSUE TITLE
Display Folksonomy Engine to every logged-in user that asks it

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8051]
### What
- We could now display Folksonomy Engine to every logged-in user that is aware of it.

### Tasks
- [ ] Add a setting to display Folksonomy Engine, but which is not proposed at user creation time
- [ ] Let users change that in their preferences
- [ ] Display Folksonomy Engine panel to those with "On" value

### Code pointers
You can find some [code pointers here](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/.github/labeler.yml). If some are missing, feel free to add them yourself in this file, or to ask them.

- https://github.com/openfoodfacts/openfoodfacts-server/blob/main/templates/web/common/includes/folksonomy_script.tt.html
- https://github.com/openfoodfacts/openfoodfacts-server/blob/main/html/js/folksonomy.js

### Part of
- #7525

**Comment by alexgarel** [comment]
@teolemon @CharlesNepote ok do you agree ?

**Comment by teolemon** [comment]
@alexgarel LGTM

**Comment by CharlesNepote** [comment]
Ok for me, but before doing this, I think we should address https://github.com/openfoodfacts/folksonomy_api/issues/128
At least we should discuss it and start to imagine solutions because it's already difficult to find the right property among 75...

**Comment by teolemon** [comment]
This is ridiculous. Following a link on the Wiki to a Folksonomy Engine key in anonymous mode does not work. 
Folksonomy Engine facets should be available to everyone.
![image](https://github.com/user-attachments/assets/7d82a4a7-e8f2-46ed-9761-09f7beae55e7)
