### ISSUE TITLE
Log key events in Matomo

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8191]
- [ ] Ensure that Matomo event names for Mobile and the Web are the same, whenever possible

```[tasklist]
### Tasks
- [ ] Instrument the "Signup successful page" in Matomo
- [ ] Add Matomo event for User clicking on account deletion - we can try to see if we can guess what caused it (eg: missing Scores, attempt to do something that failed)
- [ ] Add Matomo event for Completed sign-up - ensure the signup form is working well
- [ ] Add Matomo event for "Share product"
- [ ] Actual interaction with food preferences (we can anonymize the values, or even the attributes, but my question is: do people tweak the scoring, if so for which reasons)
- [ ] Add events for each section of the Edit page in Matomo, Clicking save as well, to see how many people give up
- [ ] Add events for knowledge panel interaction (unfolding…)
- [ ] Add events to visits to key pages (Nutri-Score, NOVA, Eco-Score, Contribute, Discover)
- [ ] Explore by button
- [ ] Sorting by button
- [ ] Clicking on PlayStore/AppStore button
- [ ] Hovering on black bar menus (user menu, tools menu, language/country menu)
- [ ] Enabling the personal ranking button
- [ ] Producer platform events (Import images, Import files…)
```
### Part of
- Better understanding users

**Comment by teolemon** [comment]
done

**Comment by LakshuCodes** [comment]
Hi ,
I’d like to work on a small, focused part of this issue.

I propose to implement the Matomo event for the “Signup successful page” (P0).

Does this sound like a good first step and is it still a priority?
Thanks.

**Comment by devsk18** [comment]
Hi @teolemon , I'd like to work on the **Personal Search** section,

 specifically: 
- adding a Matomo event for the personal ranking toggle button.

I've added the tracking call - `trackMatomoEvent()` inside `activate_preferences_switch_buttons()` in `product-preferences.js`,
- category: `personal_search`
- action: `enabled` / `disabled`

Tested locally and everything is working as expected. Can I raise a PR for this?
