### ISSUE TITLE
Move to debian bulleye

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-server#8208]
We want to do new production install on latest debian.

We should first test it in the Docker images (and on staging). We can also move to official debian image (instead of minideb).

```[tasklist]
### Tasks
- [x] use Debian Bullseye image in Dockerfile
- [x] test stagging with Debian Bullseye
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/8209
```

**Comment by alexgarel** [comment]
It's done. See https://github.com/openfoodfacts/openfoodfacts-server/pull/8234
