### ISSUE TITLE
Make the Pro platform usable by Robotoff

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-server#8486]
As part of #8319, but specific to the pro platform to allow Robotoff integration:

```[tasklist]
### Tasks
- [ ] Check that the Pro platform has a working API (probably not), fix it and add integration tests
- [ ] Check that the webhook call to Robotoff from the pro platform provides barcode parameter in the format `{org_id}/{barcode}`
- [ ] Check that OCR is working correctly on "raw" (1.jpg, 2.jpg,...) images. Currently it seems icron is not activated on the pro platform.
```

This is necessary for Robotoff to perform a number of tasks, like the automatic selection of images on the pro platform.

**Comment by manon-corneille** [comment]
Related :
https://github.com/openfoodfacts/openfoodfacts-server/issues/8202
https://github.com/openfoodfacts/openfoodfacts-server/issues/5673
