### ISSUE TITLE
Labels (Tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#8535]
### Adding new labels
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/6582
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/2818
- [ ] #8517
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/8214
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/4700

### Decypher labels
- [ ] Create opportunities for crowdsourced contributions to labels decyphering
- [ ] Allow Wikidata editing from Open Food Facts with a Wikimedia account
- [ ] Finish the grouping of labels into labels_categories
- [ ] Add a root label knowledge panels
- [ ] Visually group labels by labels_category
- [ ] Create one knowledge panel per labels category
- [ ] Create mockup of knowledge panel for labels

### Turn labels into a data source for other parts of Open Food Facts (Knowledge panels, Attributes, Computed values)
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/4512
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/1105
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/4264
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/1053

### Grow Wikipedia and Wikidata knowledge on food labels
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/1022
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/8045
- [ ] Allow Wikidata editing from Open Food Facts with a Wikimedia account Allow Wikidata editing from Open Food Facts with a Wikimedia account

### Create a data model for labels
- [ ] image
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/1022
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/2996

### Part of
- #5493 
- Taxonomies
