### ISSUE TITLE
Improve ingredient parsing (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9096]
### What

- [ ] Break down this list into thematic sections

```[tasklist]
### Improve parsing
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/5249
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/4948
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/4666
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/6517
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/6516
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/6132
- [x] https://github.com/openfoodfacts/openfoodfacts-server/issues/5369
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/5546
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/5370
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/5199
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3065
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3833
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3819
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3642
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3592
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/4905
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/4461
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3115
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3030
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/944
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3392
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3570
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3405
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/5376
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/2867
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/4232
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3909
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3905
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3738
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3432
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3960
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3808
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3962
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/2936
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3625
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3959
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3187
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3089
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/2989
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/2988
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/5980
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3829
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3932
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3297
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3924
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3839
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3643
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3820
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3589
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3617
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3678
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3252
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3922
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/3882
```

### Part of
- #5706
