### ISSUE TITLE
Integrate links to Hunger Games wherever possible (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9099]
### Integrate links to Hunger Games wherever possible
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/pull/7828
- [ ] https://github.com/openfoodfacts/facets-knowledge-panels/issues/137
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/pull/5639

### Part of
- openfoodfacts/openfoodfacts-server#5529

**Comment by DanieliusAsm** [comment]
I think also adding a button here that redirects to Hunger games logos search [for example](https://hunger.openfoodfacts.org/logos/search?barcode=4770477227540). Basically this link would take you and show you all logos that this specific barcode has and then you can annotate and add new brands never before seen on Hunger games.

When I was going through Lithuanian products to annotate and add new brands I had to open each product individually and then copy the barcode and then paste it in the Hunger games logos to see the logos of specific barcode. That increases server load because I open so many product pages just to copy the barcode.

![image](https://github.com/openfoodfacts/openfoodfacts-server/assets/22033222/c72ed40a-f617-4d60-ad80-7cbf37fef9a9)

**Comment by teolemon** [comment]
@DanieliusAsm can you put a 👍 on the issue ?
