### ISSUE TITLE
Donation links to fix

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#9361]
### What
- They need to be fixed in Crowdin https://crowdin.com/translate/openfoodfacts/3123/en-it?filter=basic&value=3#q=https://world.openfoodfacts.org/donate-to-open-food-facts
- The NL and PT issue has been fixed here: #9331 
- The others need investigation as to why they are not deployed @stephanegigandet 

### Tasks
- [ ] https://gr.openfoodfacts.org/  to https://gr.openfoodfacts.org/dorea-se-openfoodfacts
- [ ] https://cz.openfoodfacts.org/ to https://cz.openfoodfacts.org/darujte-openfoodfacts
- [ ] https://id.openfoodfacts.org/ to https://id.openfoodfacts.org/donate-to-open-food-facts-id (not deployed)
- [ ] https://lt.openfoodfacts.org/ to https://lt.openfoodfacts.org/donate-to-open-food-facts-lt  (not deployed)
- [ ] https://kr.openfoodfacts.org/ to https://kr.openfoodfacts.org/donate-to-open-food-facts-ko
- [ ] https://nl.openfoodfacts.org/ to https://nl.openfoodfacts.org/doneren-aan-openfoodfacts (not refreshed)
- [ ] https://ro.openfoodfacts.org/ to https://ro.openfoodfacts.org/donate-to-open-food-facts-ro (not deployed)
- [ ] https://sl.openfoodfacts.org/ to https://sl.openfoodfacts.org/doniraj-k-open-food-facts
- [ ] https://ua.openfoodfacts.org/ to https://ua.openfoodfacts.org/donate-to-open-food-facts-ua (not deployed)
- [ ] https://vn.openfoodfacts.org/ to https://vn.openfoodfacts.org/donate-to-open-food-facts-vi (not deployed)

### Part of
- #5720

**Comment by raphael0202** [comment]
@teolemon This one seems solved, no?

**Comment by teolemon** [comment]
yes @raphael0202
